### PR TITLE
Chainlink Events

### PR DESCRIPTION
**Pull request by jdmaturen**
## What?
This adds Chainlink events for their data feeds on Arbitrum, Avalanche, BSC, Fantom, and Optimism.

## How? 

Event feeds pulled from https://data.chain.link/

Event structure parsed with https://nansen-contract-parser-prod.web.app/

Generated with:
https://gist.github.com/jdmaturen/6cb1d69ffc79c01be7389847635432f7

## Related PRs (optional)
Similar Ethereum mainnet PR https://github.com/blockchain-etl/ethereum-etl-airflow/pull/452

## Anything Else?

### CODE REVIEW

**Comment by jdmaturen** [comment]
Will check out the failed check.

**Comment by araa47** [comment]
Seems like its due to the use of ` " ` https://github.com/nansen-ai/evmchain-etl-table-definitions/blob/fc7d4d5eca9d786f1723ded9f2ed4abed39224d9/parse/table_definitions_fantom/chainlink/AccessControlledOffchainAggregator_event_RemovedAccess.json#L16

You may want to use `'` instead of ` " ` 

like over here

https://github.com/nansen-ai/evmchain-etl-table-definitions/blob/0e23f968eef05d8be92f6f198c86a24e53a73021/schema/default_schema.json#L85

**Comment by jdmaturen** [comment]
@araa47 thanks! script and diff updated. Checks now pass.

**Comment by jdmaturen** [comment]
@araa47 do you know where the polygon schemas live as well?

**Comment by araa47** [comment]
Awesome, thank you @jdmaturen 

The Polygon schemas live over here: https://github.com/blockchain-etl/polygon-etl/tree/main/airflow/dags/resources/stages/parse/table_definitions

**Pull request merged**
