### PR TITLE
Avalanche Benqi qi{Token} Events

### PR DESCRIPTION
**Pull request by jdmaturen**
Benqi is a money market protocol on Avalanche similar to Compound. 

Add the following events: 

 - AccrueInterest
 - Approval
 - Borrow
 - Failure
 - LiquidateBorrow
 - Mint
 - NewAdmin
 - NewComptroller
 - NewMarketInterestRateModel
 - NewPendingAdmin
 - NewProtocolSeizeShare
 - NewReserveFactor
 - Redeem
 - RepayBorrow
 - ReservesAdded
 - ReservesReduced
 - Transfer

For each of the QiTokens in their documentation: https://docs.benqi.fi/contracts#qitoken. 

~~ Tables generated with the code in https://gist.github.com/jdmaturen/578436975f11a86ed79df72309b728b3. Let me know if I should include in the repo for future use. ~~

cc @medvedev1088 @tsalvatore

### CODE REVIEW

**Comment by araa47** [comment]
Hey @jdmaturen this is a great start, but to avoid the 100+ file additions, id put each of the events in a single json table definition file with multiple addresses (addresses of the qiUSDC, qiQi, qiLink, ... tokens)

There are two ways of doing this which are described below:

**Method 1 (Cleanest)**

One way to do this cleanly without hard coding the addresses is to figure out if we can programmatically determine all the `qi` token addresses. If this is possible we could follow the approach used by Uniswap like protocols, where there is a `pairCreated` event whenever a new pool is created. 

So for example over here we determine all the pairs that have been created.

https://github.com/nansen-ai/evmchain-etl-table-definitions/blob/main/parse/table_definitions_ronin/katana/UniswapV2Factory_event_PairCreated.json#L1-L65

Then we go to using only addresses that show up in this table for `Swap` and `Transfer` since these are all new pairs. 

https://github.com/nansen-ai/evmchain-etl-table-definitions/blob/10bd938ee7d53551e5d83b2ae52e21a2ad4f12e5/parse/table_definitions_ronin/katana/UniswapV2Pair_event_Swap.json#L46

https://github.com/nansen-ai/evmchain-etl-table-definitions/blob/main/parse/table_definitions_ronin/katana/UniswapV2Pair_event_Swap.json

**Method 2**

This method involves hard-coding a list of addresses instead of a single address in the `contract_address` field on the table definition json file. 

```
        "contract_address": "SELECT * FROM UNNEST(['0x7e6d3b1161df9c9c7527f68d651b297d2fdb820b', '0x9134c9975244b46692ad9a7da36dba8734ec6da3'])",
```

https://github.com/blockchain-etl/ethereum-etl-airflow/blob/91d1aa551f1ecc14aa38beda8cfc5e6260d02a74/dags/resources/stages/parse/table_definitions/enzyme/FundDeployer_event_ReleaseStatusSet.json#L22


Please update the PR to follow one of the methods above

**Comment by jdmaturen** [comment]
Thanks @araa47 that sounds good. I will inquire if there is a place to programmatically get the addresses from. The `contract_address` field gets added to the table to disambiguate these events, yes?

**Comment by araa47** [comment]
Hey @jdmaturen yep if we set `contract_address` to `null` it would scan through all logs from all contracts. 

This can be seen to be used in the `common` datasets 
https://github.com/nansen-ai/evmchain-etl-table-definitions/blob/c7f0cf59e56ca752ec00d41ece3ca5789514a4c1/parse/table_definitions_arbitrum/common/All_event_Deposit.json#L20

In this situation however since these are all `benqi` events we are interested in, its important to disambiguate these events by either: 
1) defining a set of addresses from a sql query (like we do for Uniswap) 
2) Using unnest and hardcoding a list of addresses (if there is no programmatically way to determine this on-chain from another event) 

The main advantage of approach 1 is that we don't need to come back and update the list when a new qi{Token} might be created in the future.

**Comment by jdmaturen** [comment]
Updated to method 2 in 9bc35ea @araa47. As far as I'm aware there is no relevant on chain event to use for method 1 unfortunately.

**Review by araa47 — APPROVED** [review]

**Comment by jdmaturen** [comment]
Hi @araa47 it looks like there are no events for this: 

image

I noticed in your example the contract address is lowercase instead of the checksummed case. Do we need to update the queries to use lower case addresses?

Happy to create a new issue as well if thats easier to track.

**Comment by araa47** [comment]
Hey @jdmaturen looks like its because the addresses need to be lower cased. Can you create a new PR fixing this? I will document this in the meantime.

**Pull request merged**
