### PR TITLE
Beethovenx events 2022 mar30

### PR DESCRIPTION
**Pull request by teltelchow**
Added 6 events JSON file with updated contract address to SELECT pool FROM ref('StablePoolFactory_event_PoolCreated')

### CODE REVIEW

**Comment by medvedev1088** [comment]
Please lower case the folder name for consistency: `beethovenx`

**Comment by araa47** [comment]
I should probably add a test for this too in the Github action that can fail with warning , will create a task.

**Comment by teltelchow** [comment]
> 

@medvedev1088 Hi, I lower case the folder name to beethovenx

**Comment by medvedev1088** [comment]
@teltelchow thanks! This has been deployed.

Let me know if I can delete the old `fantom_Beethovenx` dataset

**Pull request merged**
