### PR TITLE
benqi: add qiUSDTn, qiUSDCn, qisAVAX, qiBTC.b

### PR DESCRIPTION
**Pull request by ericruleman**
Adds support for the following assets in Avalanche Benqi qi{Token} Events tables:
```
qiUSDTn: '0xd8fcDa6ec4Bdc547C0827B8804e89aCd817d56EF'
qiUSDCn: '0xB715808a78F6041E46d61Cb123C9B4A27056AE9C'
qisAVAX: '0xF362feA9659cf036792c9cb02f8ff8198E21B4cB'
qiBTC.b: '0x89a415b3D20098E6A6C8f7a59001C67BD3129821'
```

These assets were recently added to Benqi money markets.

#### How? 
I obtained the qiUSDTn & qiUSDCn addreseses at https://docs.benqi.fi/resources/contracts/benqi-liquidity-market.

Found the other two assets (unlisted in documentation) in Snowtrace:
- qiBTC.b https://snowtrace.io/token/0x89a415b3D20098E6A6C8f7a59001C67BD3129821
- qisAVAX https://snowtrace.io/token/0xF362feA9659cf036792c9cb02f8ff8198E21B4cB

#### Related PRs (optional)
Builds off [this PR](https://github.com/nansen-ai/evmchain-etl-table-definitions/pull/23), also submitted by Gauntlet.

cc @medvedev1088 @tsalvatore

### CODE REVIEW

**Comment by marcinja** [comment]
cc @araa47 @TimNooren

**Comment by TimNooren** [comment]
LGTM👍

**Comment by ericruleman** [comment]
@TimNooren Will these new assets be backfilled in BigQuery?

**Comment by TimNooren** [comment]
@ericruleman yes! I cannot do this myself at the moment, but I'll update once it's done:)

**Comment by TimNooren** [comment]
@ericruleman data should be backfilled:) I did some quick checks, and it looks good to me (your example transaction shows up). But let me know if you run into any issues.

**Comment by ericruleman** [comment]
Thanks! Just verified myself as well.

**Pull request merged**
